spring:
  application:
    name: reactive-programming
  # Only works with spring-web-mvc
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

  # ??ribbon?ribbon???reactive programming
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

circuitBreaker:
  default:
    failureRateThreshold: 30
    minimumNumberOfCalls: 10
    slidingWindowSize: 10
    waitDurationInOpenState: 5S
    timeoutDuration: 5S
    cancelRunningFuture: true
  hello:
    waitDurationInOpenState: 30S